    - name: Install MySQL
      action: apt pkg=$item state=installed
      with_items:
        - mysql-server-core-5.5
        - mysql-client-core-5.5
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client
      tags:
        - mysql

    - name: Start the MySQL service
      action: service name=mysql state=started
      tags:
        - mysql

    - name: Remove the test database
      mysql_db: name=test state=absent
      tags:
        - mysql

    - name: Create deploy user for mysql
      mysql_user: user="deploy" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT
      tags:
        - mysql

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host= "{{ item.host | default('localhost') }}" state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
      tags:
        - mysql

    - name: Copy .my.cnf file with root password credentials
      template: src=templates/my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600
      tags:
        - mysql

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
      tags:
        - mysql
